### ISSUE TITLE
Guarding against MustAuthenticateFirst errors

### ISSUE THREAD

**Issue by chadokruse** [mongodb/stitch-js-sdk#184] opened 2018-12-12 16:23 UTC
I know the Stitch SDK will retry Stitch function calls should an initial call fail (e.g due to expired token, 401 response, etc). My question: What's the recommend mechanism to ensure auth is valid PRIOR to calling a Stitch function?

The reason I ask is I'm getting intermittent `MustAuthenticateFirst` errors in the wild (aka the retry mechanism does not appear to be 100% reliable). I can't reproduce locally and the failure rate is relatively low (~5%), but figured I'd post here in case it's on the SDK side (and not just my shoddy async/await code!).

I've tried guarding using [`auth.isLoggedIn`](https://s3.amazonaws.com/stitch-sdks/js/docs/4.1.0/interfaces/stitchauth.html#isloggedin) as well as [`auth.user !== undefined`](https://s3.amazonaws.com/stitch-sdks/js/docs/4.1.0/interfaces/stitchauth.html#user), but I'm still seeing the occasional `MustAuthenticateFirst` errors.

My basic setup (it's a Vue app):
1. Initialize Stitch: `this.stitchClientObj = Stitch.initializeDefaultAppClient(stitchAppId)`
2. Login Anonymously: `this.stitchClientObj.auth.loginWithCredential(credential)`
3. Call Stitch functions to fetch data: `this.stitchClientObj.callFunction('functionName', [args])`

Code
```javascript
    initializeStitchAndLogin: async function() {
      try {
        await this.stitchSetClient();
        await this.stitchLogin();
        if (this.stitchClientObj.auth.isLoggedIn) { // <== What should this be?
          this.stitchFunctionOne(0);
          this.stitchFunctionTwo(0);
        }
      } catch (err) {
        // handle error
      }
    },

    stitchSetClient: async function() {
      if (!Stitch.hasAppClient(stitchAppId)) {
        this.stitchClientObj = await Stitch.initializeDefaultAppClient(stitchAppId);
      } else {
        this.stitchClientObj = await Stitch.defaultAppClient;
      }
      return this.stitchClientObj;
    },

    stitchLogin: async function() {
      const credential = new AnonymousCredential();
      if (!this.stitchClientObj.auth.isLoggedIn || this.stitchClientObj.auth.user === undefined) {
        return await this.stitchClientObj.auth.loginWithCredential(credential)
          .then(user => {
            return user;
          })
          .catch(err => {
            // handle error
          });
      } else {
        return true;
      }
    },

    // Both Stitch function calls follow the below pattern...
    stitchFunctionOne: function(count) {
      let retryCount = count;
      return this.stitchClientObj.callFunction('functionOne', [])
        .then(result => {
          if (result) {
              // do stuff with result
          }
        })
        .catch(err => {
          // handle error 
        });
    },
```

Stacktrace
```
stitchGetInsights
t.callFunction
t.callFunction
t.callFunction
e.t.doAuthenticatedRequestWithDecoder
e.t.doAuthenticatedRequest
e.t.prepareAuthRequest	
new e	
e [as constructor]
e.d
```

Looking at [`prepareAuthRequest`](https://github.com/mongodb/stitch-js-sdk/blob/0758f8f85631e8a085938e31122ca275404d27f2/packages/core/sdk/src/auth/internal/CoreStitchAuth.ts#L348) in the SDK source, it appears the error is thrown when `!this.isLoggedIn`. Shouldn't my guard (see above) handle that scenario?

Locally, the closest I can get to reproducing is seeing the initial 401 response by waiting a day and refreshing the page (e.g. due to an expired token). However, the Stitch SDK attempts the retries as expected and the Stitch function calls complete as expected.

My error reports suggest this is occurring in modern browsers on both PC and Mac platforms, so it's likely not an outdated browser issue.

Thanks in advance for the help!

**Comment by adamchel** [comment] 2018-12-20 21:36
Hi @chadokruse ,

Judging from your code sample, I suspect the errors are due to the fact that you're mixing `async`/`await` with Promise chains, which can lead to unexpected behavior, and for some reason, a function is being called before you are actually authenticated.

For instance, when you call
```javascript
return await this.stitchClientObj.auth.loginWithCredential(credential)
          .then(user => {
            return user;
          })
          .catch(err => {
            // handle error
          });
```

That code won't actually wait for the login to complete before returning. It will return as soon as the promise as been created, but potentially before the Promise is resolved. You would have to get rid of the `.then` and `.catch` for the `await` to actually wait for the login to complete. I would recommend 

Async programming in JS can be confusing, and in general I would personally recommend just sticking with Promises, but there are plenty of resources online that can help you if you want to read more about how to use both Promises and `async`/`await` interchangeably.

This is a decent article on the subject to get you started: https://hackernoon.com/javascript-async-await-the-good-part-pitfalls-and-how-to-use-9b759ca21cda

Hope this helps, and let me know if you have any further issues!

**Comment by chadokruse** [comment] 2018-12-20 22:21
Appreciate the insight and my apologies for the shoddy async/await code (it survived two code reviews!). Interestingly, the system has been 100% error free for the past 24 hours (first error free period since testing began a few months ago).

Putting my shoddy code aside, and in case it helps others in the future, I suppose the real question is can we developers depend on `auth.isLoggedIn` and/or `auth.user !== undefined` as proxies for a user being authenticated?   

The [docs](https://docs.mongodb.com/stitch/functions/call-a-function/#call-from-a-client-application) don't provide any guidance.

**Comment by adamchel** [comment] 2018-12-21 15:37
As far as we know, `auth.isLoggedIn` should always indicate whether a user is authenticated. The only cases I can think of where `auth.isLoggedIn` would return true but you get a `MustAuthenticateFirst` error is if one of the following occurs:

* in the time between when you make the `auth.isLoggedIn` check and the function call, the user is logged out in another asynchronous routine
* the `auth` for which you checked `isLoggedIn` is from a different `StitchAppClient` than the one for which you made a function call.

If you are seeing this behavior and it's not due to one of the above scenarios, please let us know if you can reproduce the issue.

**Comment by adamchel** [comment] 2019-02-04 23:18
Hi @chadokruse I'm closing this issue as it's been a while. Please re-open this issue if you are able to reproduce the problem, or open a new issue if you experience any other problems using the SDK. Thanks!

**Closed by adamchel** 2019-02-04 23:18 UTC

**Comment by chadokruse** [comment] 2019-07-17 22:19
Updating this issue in case it helps someone else in the future. 

I was finally able to reproduce the `MustAuthenticateFirst` error when dealing with anonymous authentication. Turns out it's not one of the two scenarios mentioned above.

I believe the root cause of the error I was seeing in the wild has to do with Stitch automatically deleting anonymous users after 90 days ([docs](https://docs.mongodb.com/stitch/authentication/anonymous/#account-linking)). The client will still show `isLoggedIn: true`, but any subsequent Stitch functions called will fail.

To replicate (using v4.5.0):
1. Have the client create a new anonymous user, e.g. 
```
const client = Stitch.initializeDefaultAppClient('xxxx-xxxxxx');
client.auth.loginWithCredential(new AnonymousCredential())
  .then(user => {
    console.log(`Logged in as anonymous user with id ${user.id}`);
    console.log(`isLoggedIn: ${user.isLoggedIn}`);
    // Call any Stitch function
    client.callFunction('anyFunction, [])... // Pseudo-code
  });
```
2. Delete the user (e.g. via Stitch UI => Users tab)
3. Refreshing the page shows `isLoggedIn: true`, but throws the `MustAuthenticateFirst` error

If you refresh again the Stitch client *then* creates a new anonymous user and the Stitch function succeeds.

Unless I'm missing something (@adamchel?), it seems we can't rely on `isLoggedIn: true` to guarantee a user is authenticated prior to calling any Stitch functions. Thus, it seems the fix is to catch the error when the Stitch function is called (Stitch returns a 401) and simply create a new anonymous user.

**Comment by adamchel** [comment] 2019-07-30 12:24
Hi @chadokruse , thanks for the follow-up!

You are correct. `isLoggedIn` is not necessarily indicative of whether the user's credentials are still valid, it simply indicates whether or not there are credentials stored for that user. In the event that the user is deleted (either automatically because it's an anonymous user after 90 days, or manually via the Stitch admin console), the client has no way of knowing that that happened until it makes a request, so for now the only way of catching that is to do what you said and catch the error.

We'll look into providing a better error cpde, perhaps that specifically clarifies that the error is due to the user being deleted.
