### ISSUE TITLE
How does browser sdk support offline scenario?

### ISSUE THREAD

**Issue by wood1986** [mongodb/stitch-js-sdk#353] opened 2020-01-13 19:19 UTC
If my web app does not have internet connection and I have some insert or update db command, will it sync when online. If no, will mongo take care of it in the future release?

**Comment by robert-cronin** [comment] 2020-01-27 06:42
possible duplcate of #195?

**Comment by tkaye407** [comment] 2020-02-02 16:19
@wood1986 yeah this looks like a duplicate of #195, for feature requests please go to https://mongodb.canny.io/mongodb-stitch

**Closed by tkaye407** 2020-02-02 16:19 UTC
